# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataStruct',
        ),
    ]
